# Generated by Django 3.1.2 on 2020-11-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('productname', models.CharField(max_length=20)),
                ('productdesc', models.TextField(max_length=5000)),
                ('price', models.IntegerField(max_length=10)),
                ('Quantity', models.IntegerField(max_length=5)),
                ('productimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
