# Generated by Django 3.1.2 on 2020-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20201105_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
