# Generated by Django 3.1.2 on 2020-11-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20201105_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productimage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
