# Generated by Django 3.1.2 on 2020-11-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_auto_20201106_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
