# Generated by Django 3.1.2 on 2020-11-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20201106_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
